.Dd May 20, 2020
.Dt README 7
.Os "Causal Agency"
.
.Sh NAME
.Nm litterbox
.Nd IRC logger
.
.Sh DESCRIPTION
.Xr litterbox 1
is a TLS-only IRC logger.
It logs events from IRC in a SQLite database,
indexing messages for full-text search.
It is intended for use with
the IRC bouncer
.Xr pounce 1 ,
but can also be used independently
as a logging bot.
.
.Pp
.Nm
targets
.Fx
and requires LibreSSL
.Pq Fl ltls
and SQLite
.Pq Fl lsqlite3 .
.Bd -literal -offset indent
make all
sudo make install PREFIX=/usr/local
.Ed
.
.Pp
On other systems,
such as macOS and Linux,
the build is configured using
.Xr pkg-config 1 .
If LibreSSL is installed
in a non-standard path, set
.Ev PKG_CONFIG_PATH appropriately.
For example:
.Bd -literal -offset indent
PKG_CONFIG_PATH=/opt/libressl/lib/pkgconfig ./configure
make all
sudo make install PREFIX=/usr/local
.Ed
.
.Sh FILES
.Bl -tag -width "litterbox.c" -compact
.It Pa database.h
database functions and schema
.It Pa litterbox.c
IRC logging
.It Pa scoop.c
query building and output formatting
.It Pa unscoop.c
log file processing
.It Pa config.c
.Xr getopt_long 3 Ns -integrated
configuration parsing
.It Pa rc.d/
.Fx
.Xr rc 8
scripts
.El
.
.Sh CONTRIBUTING
The upstream URL of this project is
.Aq Lk https://git.causal.agency/litterbox .
Contributions in any form can be sent to
.Aq Mt list+litterbox@causal.agency .
For sending patches by email, see
.Aq Lk https://git-send-email.io .
.
.Sh SEE ALSO
.Xr litterbox 1 ,
.Xr scoop 1 ,
.Xr unscoop 1
.
.Pp
IRC bouncer:
.Lk https://git.causal.agency/pounce "pounce"
