.Dd December 23, 2019
.Dt UNSCOOP 1
.Os
.
.Sh NAME
.Nm unscoop
.Nd import IRC logs
.
.Sh SYNOPSIS
.Nm
.Op Fl v
.Op Fl C Ar context
.Op Fl N Ar network
.Op Fl d Ar path
.Op Fl f Ar format
.Ar
.
.Nm
.Fl D
.Op Fl d Ar path
.
.Sh DESCRIPTION
The
.Nm
utility imports IRC logs into the
.Xr litterbox 1
database.
The network and context (channel or query) names
are inferred from the input file paths,
so
.Nm
should be run from the log directory root.
.
.Pp
The arguments are as follows:
.Bl -tag -width Ds
.It Fl C Ar context
Override the context (channel or query) name
of imported logs.
.
.It Fl D
Delete duplicate events from overlapping imports.
This operation requires SQLite version 3.25.0 or newer.
.
.It Fl N Ar network
Override the network name of the imported logs.
.
.It Fl d Ar path
Set the database path.
The database must have been initialized by
.Xr litterbox 1 .
The default path is as in
.Xr litterbox 1 .
.
.It Fl f Ar format
Set the input log format.
The default format is
.Cm generic .
.Pp
The following formats are supported:
.Bl -tag -width Ds
.It Cm catgirl
Logs from the catgirl IRC client.
.It Cm generic
Matches paths of the form
.Pa network/context/*
and messages of the following forms:
.Bd -literal -offset indent
[timestamp] <nick> privmsg
[timestamp] -nick- notice
[timestamp] * nick action
.Ed
.It Cm irc
IRC protocol messages tagged with the IRCv3.2
.Sy server-time
extension.
Network and context must be set with
.Fl N
and
.Fl C .
.It Cm textual
Logs from the Textual IRC client.
.El
.
.It Fl v
Log SQL to standard error.
.El
.
.Sh EXAMPLES
.Bd -literal
find catgirl -type f -name '*.log' -print0 | xargs -0 unscoop -f catgirl
find Textual -type f -name '*.txt' -not -path '*/Console/*' -print0 \e
	| xargs -0 unscoop -f textual
.Ed
.
.Sh SEE ALSO
.Xr litterbox 1 ,
.Xr scoop 1
.
.Sh AUTHORS
.An June Bug Aq Mt june@causal.agency
.
.Sh BUGS
Send mail to
.Aq Mt june@causal.agency
or join
.Li #ascii.town
on
.Li chat.freenode.net .
